services:
  #API .NET
  api:
    container_name: rastreamento-api
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=RastreamentoCargasDb;User Id=sa;Password=Password@123;TrustServerCertificate=True
    depends_on:
      - sql-server-db

  # SQL Server
  sql-server-db:
    container_name: rastreamento-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123" 
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
    driver: local